#!/bin/bash -e

. common

if [[ ! -f "./environment" ]]; then
  if [ $# -lt 6 ]; then
    echo "Usage: ./add-org-spaces <System Domain> <Ops Manager Host> <Ops Manager Username> <Ops Manager Password> <Org> <Space>"
    exit 1
  fi

  export SYSTEM_DOMAIN=$1
  export OPS_MANAGER_HOST=$2
  export OPS_MGR_ADMIN_USERNAME=$3
  export OPS_MGR_ADMIN_PASSWORD=$4
  export ORG=$5
  export SPACE=$6
else
  source environment

  if [ $# -lt 2 ]; then
    echo "Usage: ./add-org-spaces <Org> <Space>"
    exit 1
  fi

  export ORG=$1
  export SPACE=$2
fi

export API_ENDPOINT=api.$SYSTEM_DOMAIN

fetch_cf_deployment_guid
RESPONSE=$(fetch_credentials .uaa.admin_credentials)
CF_ADMIN_USERNAME=`echo $RESPONSE | jq '.credential.value.identity' | tr -d '"'`
CF_ADMIN_PASSWORD=`echo $RESPONSE | jq '.credential.value.password' | tr -d '"'`

cf api --skip-ssl-validation $API_ENDPOINT
cf login -u $CF_ADMIN_USERNAME -p $CF_ADMIN_PASSWORD -o system -s system

cf co $ORG
cf create-space $SPACE -o $ORG

cf logout
