#!/bin/bash

# 1. UAA url
# 2. Admin username
# 3. Admin secret
# 4. User to promote as admin

if [ $# -lt 4 ]; then
  echo "Usage: ./assign-admin-privileges <System Domain> <admin username> <admin-secret> <user-to-promote>"
  exit 1
fi

export LOG_FILE=/tmp/assign-admin-privileges.log
export SYSTEM_DOMAIN=$1
export UAA_ENDPOINT=uaa.$SYSTEM_DOMAIN
export UAA_ADMIN_USER=$2
export UAA_ADMIN_PWD=$3
export USER_TO_PROMOTE=$4

echo "Log location is: $LOG_FILE"

uaac target $UAA_ENDPOINT >> /tmp/assign-admin-privileges.log 2>&1
uaac token client get $UAA_ADMIN_USER -s $UAA_ADMIN_PWD >> $LOG_FILE 2>&1
uaac contexts >> $LOG_FILE 2>&1

uaac member add cloud_controller.admin $USER_TO_PROMOTE >> $LOG_FILE 2>&1
uaac member add uaa.admin $USER_TO_PROMOTE >> $LOG_FILE 2>&1
uaac member add scim.read $USER_TO_PROMOTE >> $LOG_FILE 2>&1
uaac member add scim.write $USER_TO_PROMOTE >> $LOG_FILE 2>&1
uaac member add password.write $USER_TO_PROMOTE >> $LOG_FILE 2>&1
uaac member add openid $USER_TO_PROMOTE >> $LOG_FILE 2>&1

uaac token delete

echo "You've sucessfully handed over the power of admin to $USER_TO_PROMOTE. Mission Accomplished!!"
