#!/bin/bash --login

. common

validate_software() {
	echo "VALIDATE MANDATORY TOOLS"

	INSTALLED_BOSH=`which bosh`
	if [ -z "$INSTALLED_BOSH" ]; then
		echo "BOSH CLI not installed"
		exit 1
	fi

#	INSTALLED_PG_DUMP=`which pg_dump`
#	if [ -z "$INSTALLED_PG_DUMP" ]; then
#		echo "pg_dump utility not installed"
#		exit 1
#	fi

	INSTALLED_JAVA=`which java`
	if [ -z "$INSTALLED_JAVA" ]; then
		echo "Java JRE is missing"
		exit 1
	fi

	INSTALLED_MYSQL=`which mysqldump`
	if [ -z "$INSTALLED_MYSQL" ]; then
		echo "mysqldump utility is missing"
		exit 1
	fi
}

verify_deployment_backedUp() {
	echo "VERIFY CF DEPLOYMENT MANIFEST"
	export CF_DEPLOYMENT_NAME=`bosh deployments | grep "cf-" | cut -d '|' -f 2 | tr -s ' ' | grep "cf-" | tr -d ' ' | head -1`
	export CF_DEPLOYMENT_FILE_NAME=$CF_DEPLOYMENT_NAME.yml

	echo "FILES LOOKING FOR $CF_DEPLOYMENT_NAME $CF_DEPLOYMENT_FILE_NAME"

	if [ -f $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME ]; then
		echo "file exists"
	else
		echo "file does not exist"
		bosh download manifest $CF_DEPLOYMENT_NAME $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME
	fi
}

export_Encryption_key() {
	echo "EXPORT DB ENCRYPTION KEY"
	grep -E 'db_encryption_key' $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME | cut -d ':' -f 2 | sort -u > $WORK_DIR/cc_db_encryption_key.txt
}

bosh_status() {
	echo "EXECUTE BOSH STATUS"
	bosh status > $WORK_DIR/bosh_status.txt
	export BOSH_UUID=`grep UUID $WORK_DIR/bosh_status.txt | cut -d 'D' -f 2 | tr -d ' ' | sort -u`

	export UUID_EXISTS=`grep -Fxq $BOSH_UUID $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME`
	if [[ -z $UUID_EXISTS ]]; then
		echo "UUID Matches"
	else
		echo "UUID Mismatch"
		exit 1
	fi

	rm -rf $WORK_DIR/bosh_status.txt
}

set_bosh_deployment() {
    echo "SET THE BOSH DEPLOYMENT"
	bosh deployment $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME
}

export_bosh_vms() {
    echo "EXPORT BOSH VMS"
	OUTPUT=`bosh vms | grep "cloud_controller-partition-*" | cut -d '|' -f 2 | cut -d '(' -f 1 | tr -d ' '`
	echo $OUTPUT > $WORK_DIR/bosh-vms.txt
}

stop_cloud_controller() {
	echo "STOPPING CLOUD CONTROLLER"
	OUTPUT=`cat $WORK_DIR/bosh-vms.txt`

	for word in $OUTPUT
	do
		JOB=`echo $word | cut -d '/' -f 1`
		INDEX=`echo $word | cut -d '/' -f 2`

		bosh -n stop $JOB $INDEX --force
	done
}

export_db() {
	output=`sh appassembler/bin/app $WORK_DIR/installation.yml $1 $2 $3`

	export USERNAME=`echo $output | cut -d '|' -f 1`
	export PGPASSWORD=`echo $output | cut -d '|' -f 2`
	export IP=`echo $output | cut -d '|' -f 3`

	export PORT=$4
	export DB=$5
	export DB_FILE=$6

	pg_dump -h $IP -U $USERNAME -p $4 $5 > $6

}

export_nfs_server() {
	echo "EXPORT NFS-SERVER"

	NFS_IP=`bosh vms $CF_DEPLOYMENT_NAME | grep nfs | cut -d '|' -f 6 | tr -d ' '`

	ssh-keygen -R $NFS_IP

	/usr/bin/expect -c "
		set timeout -1

		spawn scp -i $BOSH_PRIVATE_KEY_PATH -rp vcap@$NFS_IP:/var/vcap/store/shared $NFS_DIR

		expect {
			-re ".*Are.*.*yes.*no.*" {
				send yes\r ;
				interact
			}
		}

		exit
	"
}

start_cloud_controller() {
	echo "STARTING CLOUD CONTROLLER"
	OUTPUT=`cat $WORK_DIR/bosh-vms.txt`

	for word in $OUTPUT
	do
		JOB=`echo $word | cut -d '/' -f 1`
		INDEX=`echo $word | cut -d '/' -f 2`

		bosh -n start $JOB $INDEX --force
	done

}

export_mysqldb() {

	export USERNAME='root'
	export PASSWORD=`cat $WORK_DIR/$CF_DEPLOYMENT_FILE_NAME | grep "user=root --password=" | tr -s ' ' | cut -d '=' -f 3 | cut -d ' ' -f 1`
	export IP=`bosh vms $CF_DEPLOYMENT_NAME | grep mysql-partition* | cut -d '|' -f 6 | tr -d ' '`

	DB_FILE=$DATABASE_DIR/mysql.sql

	echo "[mysqldump]
user=$USERNAME
password=$PASSWORD" > ~/.my.cnf

	echo "EXPORT MySQL DB"

	mysqldump -u $USERNAME -h $IP --all-databases > $DB_FILE

  rm ~/.my.cnf

}

export_installation() {
	if [[ "Y" = "$COMPLETE_BACKUP" || "y" = "$COMPLETE_BACKUP" ]]; then
		CONNECTION_URL=https://$OPS_MANAGER_HOST/api/installation_asset_collection

		echo "EXPORT INSTALLATION FILES FROM " $CONNECTION_URL

		curl "$CONNECTION_URL" -X GET -u $OPS_MGR_ADMIN_USERNAME:$OPS_MGR_ADMIN_PASSWORD --insecure -k -o $WORK_DIR/installation.zip
	fi
}

zip_all_together() {
	cd $WORK_DIR
	cd ..
	cmd=`tar -zcvf $BACKUP_DIR_NAME.tar.gz $BACKUP_DIR_NAME`
	echo "Compressed the backup into $BACKUP_DIR_NAME.tar.gz"
	cmd=`rm -rf $WORK_DIR`
}

execute() {
	validate_software
	bosh_login_wo_certs
	verify_deployment_backedUp
	export_Encryption_key
	bosh_status
	set_bosh_deployment
	export_bosh_vms
	stop_cloud_controller
	export_nfs_server
	export_mysqldb
	start_cloud_controller
	zip_all_together
	bosh logout
}

if [[ ! -f "./environment.sh" ]]; then

	if [ $# -lt 5 ]; then
		echo "Usage: ./backup_script.sh <BOSH DIRECTOR IP> <BOSH DIRECTOR USER> <BOSH DIRECTOR PASSWORD> <BOSH PRIVATE KEY PATH> <OUTPUT DIR> <COMPLETE BACKUP>"
		printf "\t %s \t\t\t %s \n" "BOSH DIRECTOR IP:" "Bosh Director IP"
		printf "\t %s \t\t\t %s \n" "BOSH DIRECTOR USER:" "BOSH Director Username"
		printf "\t %s \t\t %s \n" "BOSH DIRECTOR PASSWORD:" "BOSH Director Password"
    printf "\t %s \t\t %s \n" "BOSH PRIVATE KEY PATH:" "BOSH Private Key Location"
		printf "\t %s \t\t\t\t %s \n" "OUTPUT DIR:" "Backup Directory"
		printf "\t %s \t\t\t %s \n" "COMPLETE BACKUP:" "Specify 'Y' for complete backup"
		exit 1
	fi

	export DATE=`date +%Y_%m_%d`
  export BOSH_DIRECTOR_IP=$1
	export DIRECTOR_USERNAME=$2
  export DIRECTOR_PASSWORD=$3
  export BOSH_PRIVATE_KEY_PATH=$4
	export BACKUP_DIR_NAME=Backup_$DATE
	export WORK_DIR=$5/$BACKUP_DIR_NAME
	export NFS_DIR=$WORK_DIR/nfs_share
	export DEPLOYMENT_DIR=$WORK_DIR/deployments
	export DATABASE_DIR=$WORK_DIR/database

	export COMPLETE_BACKUP='N' #$5

else
	source "./environment.sh"
fi

mkdir -p $WORK_DIR
mkdir -p $NFS_DIR
mkdir -p $DEPLOYMENT_DIR
mkdir -p $DATABASE_DIR

execute

echo "$DATE - BACKUP SUCCESSFUL"
