#!/bin/bash -e

remove_unused_products() {
	echo "REMOVING USUSED PRODUCTS"
	CURL_URL=/api/v0/available_products
	om -t https://$OPS_MANAGER_HOST -u $OPS_MGR_ADMIN_USERNAME -p $OPS_MGR_ADMIN_PASSWORD -k curl -p "$CURL_URL" -x DELETE
}

execute() {
	remove_unused_products
}

if [[ ! -f "./environment" ]]; then
	if [ $# -lt 3 ]; then
		echo "Usage: ./delete-unused-products <OPS MGR HOST or IP> <OPS MGR ADMIN USER> <OPS MGR ADMIN PASSWORD>"
		printf "\t %s \t\t\t %s \n" "OPS MGR HOST or IP:" "OPS Manager Host or IP"
		printf "\t %s \t\t\t %s \n" "OPS MGR ADMIN USER:" "OPS Manager Admin Username"
		printf "\t %s \t\t %s \n" "OPS MGR ADMIN PASSWORD:" "OPS Manager Admin Password"
		exit 1
	fi

	export OPS_MANAGER_HOST=$1
	export OPS_MGR_ADMIN_USERNAME=$2
	export OPS_MGR_ADMIN_PASSWORD=$3
else
	source environment
fi

export DATE=`date +%Y_%m_%d`

execute

echo "$DATE - CLEANUP SUCCESSFUL"
