#!/bin/bash -e

if [[ ! -f "./environment" ]]; then
  if [ $# -lt 4 ]; then
    echo "Usage: ./import-single-user <System Domain> <Ops Manager Host> <Ops Manager Username> <Ops Manager Password>"
    exit 1
  fi

  export SYSTEM_DOMAIN=$1
  export OPS_MANAGER_HOST=$2
  export OPS_MGR_ADMIN_USERNAME=$3
  export OPS_MGR_ADMIN_PASSWORD=$4
else
  source environment
fi

export LOG_FILE=/tmp/import-users.log
echo "Log location is: $LOG_FILE"

export API_ENDPOINT=api.$SYSTEM_DOMAIN
export UAA_ENDPOINT=uaa.$SYSTEM_DOMAIN

fetch_cf_deployment_guid
RESPONSE=$(fetch_credentials .uaa.admin_credentials)
CF_ADMIN_USERNAME=`echo $RESPONSE | jq '.credential.value.identity' | tr -d '"'`
CF_ADMIN_PASSWORD=`echo $RESPONSE | jq '.credential.value.password' | tr -d '"'`

cf api --skip-ssl-validation $API_ENDPOINT >> $LOG_FILE 2>&1
cf login -u $CF_ADMIN_USERNAME -p $CF_ADMIN_PASSWORD

RESPONSE=$(fetch_credentials .uaa.admin_client_credentials)
UAA_ADMIN_USERNAME=`echo $RESPONSE | jq '.credential.value.identity' | tr -d '"'`
UAA_ADMIN_PASSWORD=`echo $RESPONSE | jq '.credential.value.password' | tr -d '"'`

uaac target --skip-ssl-validation $UAA_ENDPOINT >> $LOG_FILE 2>&1
uaac token client get $UAA_ADMIN_USERNAME -s $UAA_ADMIN_PASSWORD >> $LOG_FILE 2>&1

IFS="#"
while read f1 f2 f3 f4 f5 f6 f7
do
        echo "UID is                      : $f1"
        echo "Email is                    : $f2"
        echo "UserName is                 : $f3"
        echo "OrgName  is                 : $f4"
        echo "Org Permissions  is         : $f5"
        echo "SpaceName is                : $f6"
        echo "Space Permission is         : $f7"

        RESPONSE=`uaac curl -H "Content-Type: application/json" -k  /Users -X POST -d '{"userName":"'"$f3"'","emails":[{"value":"'"$f2"'"}],"origin":"ldap","externalId":"'"$f1"'"}'`

        ID=`echo $RESPONSE | grep "id" | head -3 | tail -1 | cut -d ":" -f2 | cut -d " " -f2 | cut -d "," -f1`
        echo $ID

        IMPORT_USER_TO_CC=`cf curl /v2/users -d '{"guid":"'"$ID"'"}' -X POST`

        IFS="|" read -a orgperms <<< "$f5"

        for orgperm in "${orgperms[@]}"
        do
          cf set-org-role $f3 $f4 $orgperm
        done

        IFS="|" read -a spaceperms <<< "$f7"

        for spaceperm in "${spaceperms[@]}"
        do
          cf set-space-role $f3 $f4 $f6 $spaceperm
        done

done < users.csv

uaac token delete
cf logout
