#!/bin/bash

if [ $# -lt 5 ]; then
  echo "Usage: ./import-users.sh <System Domain> <Apps Manager Admin Username> <Apps Manager Admin Password> <UAA Admin Username> <UAA Admin Client Credentials>"
  exit 1
fi


export LOG_FILE=/tmp/import-users.log
echo "Log location is: $LOG_FILE"

export SYSTEM_DOMAIN=$1
export API_ENDPOINT=api.$SYSTEM_DOMAIN
export UAA_ENDPOINT=uaa.$SYSTEM_DOMAIN
export APPS_MGR_ADMIN_USER=$2
export APPS_MGR_ADMIN_PWD=$3
export UAA_ADMIN_USER=$4
export UAA_ADMIN_PWD=$5

cf api --skip-ssl-validation $API_ENDPOINT >> $LOG_FILE 2>&1
cf login -u $APPS_MGR_ADMIN_USER -p $APPS_MGR_ADMIN_PWD

uaac target --skip-ssl-validation $UAA_ENDPOINT >> $LOG_FILE 2>&1
uaac token client get $UAA_ADMIN_USER -s $UAA_ADMIN_PWD >> $LOG_FILE 2>&1

IFS="#"
while read f1 f2 f3 f4 f5 f6 f7
do
        echo "UID is                      : $f1"
        echo "Email is                    : $f2"
        echo "UserName is                 : $f3"
        echo "OrgName  is                 : $f4"
        echo "Org Permissions  is         : $f5"
        echo "SpaceName is                : $f6"
        echo "Space Permission is         : $f7"

        RESPONSE=`uaac curl -H "Content-Type: application/json" -k  /Users -X POST -d '{"userName":"'"$f3"'","emails":[{"value":"'"$f2"'"}],"origin":"ldap","externalId":"'"$f1"'"}'`
#	echo $RESPONSE
        ID=`echo $RESPONSE | grep "id" | head -3 | tail -1 | cut -d ":" -f2 | cut -d " " -f2 | cut -d "," -f1`
        echo $ID

        IMPORT_USER_TO_CC=`cf curl /v2/users -d '{"guid":"'"$ID"'"}' -X POST`
#	echo $IMPORT_USER_TO_CC >> $LOG_FILE 2>&1
	      #echo $IMPORT_USER_TO_CC

        IFS="|" read -a orgperms <<< "$f5"

        for orgperm in "${orgperms[@]}"
        do
          cf set-org-role $f3 $f4 $orgperm
        done

        IFS="|" read -a spaceperms <<< "$f7"

        for spaceperm in "${spaceperms[@]}"
        do
          cf set-space-role $f3 $f4 $f6 $spaceperm
        done

done < users.csv

uaac token delete
cf logout
